# 🐼 Pandas - Class 2: DataFrame Basics
Welcome to **Class 2**. Today we’ll learn how to **inspect**, **select**, and **organize** data inside a DataFrame.

## 1 Inspecting Data
Quick ways to understand your dataset:
- `head(n)` → first *n* rows (default 5)
- `tail(n)` → last *n* rows
- `info()` → columns, non-null counts, and dtypes
- `shape` → (rows, columns)
- `dtypes` → data type of each column

In [44]:
import pandas as pd

# Create a small DataFrame
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)
b.head(3)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79

In [45]:
b.tail(3)

      Name  Age  Score
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [46]:
b.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

In [47]:
b.shape

(5, 3)

In [48]:
b.dtypes

Name       str
Age      int64
Score    int64
dtype: object

## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:
- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]`
Tip: `:` means "all rows/columns" in that dimension.

In [49]:
b["Name"]

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: str

In [50]:
b[["Name","Score"]]

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     79
3    David     85
4     Emma     95

In [51]:
b.loc[0]

Name     Alice
Age         25
Score       88
Name: 0, dtype: object

In [52]:
b.loc[0,"Score"]

np.int64(88)

In [53]:
b.loc[1:4,["Age","Score"]]

   Age  Score
1   30     92
2   35     79
3   40     85
4   22     95

## 3 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array (read-only; prefer using DataFrame ops)

In [54]:
b.index

RangeIndex(start=0, stop=5, step=1)

In [55]:
b.columns

Index(['Name', 'Age', 'Score'], dtype='str')

In [56]:
b.values

array([['Alice', 25, 88],
       ['Bob', 30, 92],
       ['Charlie', 35, 79],
       ['David', 40, 85],
       ['Emma', 22, 95]], dtype=object)

## 4 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as index → `df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)`
 If you don't use `inplace=True`, remember to assign the result back to a variable.

In [57]:

c=b.rename(columns={"Score":"Marks"})
c

      Name  Age  Marks
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95

In [58]:
positions=["first","second","third","fourth","fifth"]
b.set_axis(positions,axis=0)

           Name  Age  Score
first     Alice   25     88
second      Bob   30     92
third   Charlie   35     79
fourth    David   40     85
fifth      Emma   22     95

In [59]:
b.set_index("Name")

         Age  Score
Name
Alice     25     88
Bob       30     92
Charlie   35     79
David     40     85
Emma      22     95

In [60]:
b.reset_index()

   index     Name  Age  Score
0      0    Alice   25     88
1      1      Bob   30     92
2      2  Charlie   35     79
3      3    David   40     85
4      4     Emma   22     95

## 5 Basic Attributes Recap
- `df.columns` → names of all columns
- `df.index` → row labels
- `df.values` → NumPy array (data only)
These are handy for quick checks and loops (though vectorized ops are preferred).

In [61]:
b.columns

Index(['Name', 'Age', 'Score'], dtype='str')

In [62]:
b.index

RangeIndex(start=0, stop=5, step=1)

In [63]:
b.values

array([['Alice', 25, 88],
       ['Bob', 30, 92],
       ['Charlie', 35, 79],
       ['David', 40, 85],
       ['Emma', 22, 95]], dtype=object)

## Mini Practice
1. Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
2. Show the first 3 rows, last 2 rows, and the info.
3. Select a sub-DataFrame with only 2 columns.
4. Rename one column and set any column as index, then reset it back.
5. Print `df.shape`, `df.dtypes`, and `df.columns`.

In [64]:
import pandas as pd

# Create a DataFrame with at least 5 rows & 4 columns (mix of numbers + text)
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)

# Show the first 3 rows, last 2 rows, and info
# your code here

# Select a sub-DataFrame with only 2 columns
# your code here

# Rename one column and set any column as index, then reset it back
# your code here

# Print df.shape, df.dtypes, and df.columns
# your code here

---
## ✅ Summary
- You learned to **inspect** a DataFrame (`head`, `tail`, `info`, `shape`, `dtypes`).
- You practiced **selecting** columns/rows using `[]`, `.loc`, and `.iloc`.
- You explored **index/columns** and basic attributes.
- You **renamed** columns and **set/reset** an index.

Next up: **Data Cleaning Essentials** (missing values, types, duplicates).

In [65]:
data = {
    "Name": ["Ram", "Shyam", "Hari", "Sita", "Gita", "Mohan", "Rita", "Kiran", "Anil", "Sunita"],
    "Age": [20, 21, 19, 22, 20, 23, 21, 19, 22, 20],
    "Marks": [85, 78, 92, 88, 95, 76, 89, 91, 83, 87],
    "City": ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Chitwan",
             "Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Butwal"],
    "Grade": ["A", "B", "A+", "A", "A+", "B", "A", "A+", "A", "A"]
}

df = pd.DataFrame(data)
df

     Name  Age  Marks        City Grade
0     Ram   20     85   Kathmandu     A
1   Shyam   21     78     Pokhara     B
2    Hari   19     92    Lalitpur    A+
3    Sita   22     88   Bhaktapur     A
4    Gita   20     95     Chitwan    A+
5   Mohan   23     76   Kathmandu     B
6    Rita   21     89     Pokhara     A
7   Kiran   19     91    Lalitpur    A+
8    Anil   22     83  Biratnagar     A
9  Sunita   20     87      Butwal     A

In [66]:
df.head(3)

    Name  Age  Marks       City Grade
0    Ram   20     85  Kathmandu     A
1  Shyam   21     78    Pokhara     B
2   Hari   19     92   Lalitpur    A+

In [67]:
df.tail(3)

     Name  Age  Marks        City Grade
7   Kiran   19     91    Lalitpur    A+
8    Anil   22     83  Biratnagar     A
9  Sunita   20     87      Butwal     A

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     str
 1   Age     10 non-null     int64
 2   Marks   10 non-null     int64
 3   City    10 non-null     str
 4   Grade   10 non-null     str
dtypes: int64(2), str(3)
memory usage: 669.0 bytes

In [69]:
df.loc[:,["Name","City"]]

     Name        City
0     Ram   Kathmandu
1   Shyam     Pokhara
2    Hari    Lalitpur
3    Sita   Bhaktapur
4    Gita     Chitwan
5   Mohan   Kathmandu
6    Rita     Pokhara
7   Kiran    Lalitpur
8    Anil  Biratnagar
9  Sunita      Butwal

In [70]:
df.rename(columns={"Grade":"GPA"},inplace=True)
df

     Name  Age  Marks        City GPA
0     Ram   20     85   Kathmandu   A
1   Shyam   21     78     Pokhara   B
2    Hari   19     92    Lalitpur  A+
3    Sita   22     88   Bhaktapur   A
4    Gita   20     95     Chitwan  A+
5   Mohan   23     76   Kathmandu   B
6    Rita   21     89     Pokhara   A
7   Kiran   19     91    Lalitpur  A+
8    Anil   22     83  Biratnagar   A
9  Sunita   20     87      Butwal   A

In [71]:
df.set_index("Name",inplace=True)
df

        Age  Marks        City GPA
Name
Ram      20     85   Kathmandu   A
Shyam    21     78     Pokhara   B
Hari     19     92    Lalitpur  A+
Sita     22     88   Bhaktapur   A
Gita     20     95     Chitwan  A+
Mohan    23     76   Kathmandu   B
Rita     21     89     Pokhara   A
Kiran    19     91    Lalitpur  A+
Anil     22     83  Biratnagar   A
Sunita   20     87      Butwal   A

In [72]:
df.reset_index()

     Name  Age  Marks        City GPA
0     Ram   20     85   Kathmandu   A
1   Shyam   21     78     Pokhara   B
2    Hari   19     92    Lalitpur  A+
3    Sita   22     88   Bhaktapur   A
4    Gita   20     95     Chitwan  A+
5   Mohan   23     76   Kathmandu   B
6    Rita   21     89     Pokhara   A
7   Kiran   19     91    Lalitpur  A+
8    Anil   22     83  Biratnagar   A
9  Sunita   20     87      Butwal   A