# 🐼 Pandas - Class 8: Working with Time Series
Welcome to **Class 8** of our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [2]:
import pandas as pd

data = {
    "OrderID": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015,
        1016, 1017, 1018, 1019, 1020,
        1021, 1022, 1023, 1024, 1025
    ],
    "OrderDate": [
        "2026-01-05", "2026-01-07", "2026-01-08", "2026-01-10", "2026-01-12",
        "2026-01-15", "2026-01-17", "2026-01-20", "2026-01-22", "2026-01-25",
        "2026-02-01", "2026-02-03", "2026-02-05", "2026-02-08", "2026-02-10",
        "2026-02-12", "2026-02-15", "2026-02-18", "2026-02-20", "2026-02-22",
        "2026-03-01", "2026-03-04", "2026-03-07", "2026-03-10", "2026-03-12"
    ],
    "Customer": [
        "Ram Sharma", "Sita Thapa", "Hari Karki", "Ram Sharma", "Anita Rai",
        "Bikash Joshi", "Sita Thapa", "Nabin Shrestha", "Anita Rai", "Hari Karki",
        "Priya Shah", "Ram Sharma", "Bikash Joshi", "Sita Thapa", "Nabin Shrestha",
        "Hari Karki", "Priya Shah", "Anita Rai", "Ram Sharma", "Bikash Joshi",
        "Nabin Shrestha", "Priya Shah", "Sita Thapa", "Hari Karki", "Anita Rai"
    ],
    "Amount": [
        1500, 2500, 800, 3200, 1200,
        4500, 1800, 2700, 950, 3600,
        5200, 2100, 1750, 4000, 2900,
        1300, 6000, 2200, 3400, 1600,
        3100, 4800, 1950, 2600, 3700
    ]
}

df = pd.DataFrame(data)
print(df)

    OrderID   OrderDate        Customer  Amount
0      1001  2026-01-05      Ram Sharma    1500
1      1002  2026-01-07      Sita Thapa    2500
2      1003  2026-01-08      Hari Karki     800
3      1004  2026-01-10      Ram Sharma    3200
4      1005  2026-01-12       Anita Rai    1200
5      1006  2026-01-15    Bikash Joshi    4500
6      1007  2026-01-17      Sita Thapa    1800
7      1008  2026-01-20  Nabin Shrestha    2700
8      1009  2026-01-22       Anita Rai     950
9      1010  2026-01-25      Hari Karki    3600
10     1011  2026-02-01      Priya Shah    5200
11     1012  2026-02-03      Ram Sharma    2100
12     1013  2026-02-05    Bikash Joshi    1750
13     1014  2026-02-08      Sita Thapa    4000
14     1015  2026-02-10  Nabin Shrestha    2900
15     1016  2026-02-12      Hari Karki    1300
16     1017  2026-02-15      Priya Shah    6000
17     1018  2026-02-18       Anita Rai    2200
18     1019  2026-02-20      Ram Sharma    3400
19     1020  2026-02-22    Bikash Joshi    1600
20     1021  2026-03-01  Nabin Shrestha    3100
21     1022  2026-03-04      Priya Shah    4800
22     1023  2026-03-07      Sita Thapa    1950
23     1024  2026-03-10      Hari Karki    2600
24     1025  2026-03-12       Anita Rai    3700

In [3]:
df.dtypes

OrderID      int64
OrderDate      str
Customer       str
Amount       int64
dtype: object

In [4]:
pd.to_datetime(df["OrderDate"],errors="coerce")

0    2026-01-05
1    2026-01-07
2    2026-01-08
3    2026-01-10
4    2026-01-12
5    2026-01-15
6    2026-01-17
7    2026-01-20
8    2026-01-22
9    2026-01-25
10   2026-02-01
11   2026-02-03
12   2026-02-05
13   2026-02-08
14   2026-02-10
15   2026-02-12
16   2026-02-15
17   2026-02-18
18   2026-02-20
19   2026-02-22
20   2026-03-01
21   2026-03-04
22   2026-03-07
23   2026-03-10
24   2026-03-12
Name: OrderDate, dtype: datetime64[us]

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('M').mean()` or other rules ('D', 'W', 'Y').
- Useful for aggregating data by time periods.

In [5]:
df["OrderDate"]=pd.to_datetime(df["OrderDate"],errors="coerce")

In [9]:
df_idx=df.set_index("OrderDate")
df_idx

            OrderID        Customer  Amount
OrderDate
2026-01-05     1001      Ram Sharma    1500
2026-01-07     1002      Sita Thapa    2500
2026-01-08     1003      Hari Karki     800
2026-01-10     1004      Ram Sharma    3200
2026-01-12     1005       Anita Rai    1200
2026-01-15     1006    Bikash Joshi    4500
2026-01-17     1007      Sita Thapa    1800
2026-01-20     1008  Nabin Shrestha    2700
2026-01-22     1009       Anita Rai     950
2026-01-25     1010      Hari Karki    3600
2026-02-01     1011      Priya Shah    5200
2026-02-03     1012      Ram Sharma    2100
2026-02-05     1013    Bikash Joshi    1750
2026-02-08     1014      Sita Thapa    4000
2026-02-10     1015  Nabin Shrestha    2900
2026-02-12     1016      Hari Karki    1300
2026-02-15     1017      Priya Shah    6000
2026-02-18     1018       Anita Rai    2200
2026-02-20     1019      Ram Sharma    3400
2026-02-22     1020    Bikash Joshi    1600
2026-03-01     1021  Nabin Shrestha    3100
2026-03-04     1022      Priya Shah    4800
2026-03-07     1023      Sita Thapa    1950
2026-03-10     1024      Hari Karki    2600
2026-03-12     1025       Anita Rai    3700

In [12]:
df_idx.resample("ME")["Amount"].sum()

OrderDate
2026-01-31    22750
2026-02-28    30450
2026-03-31    16150
Freq: ME, Name: Amount, dtype: int64

In [14]:
df_idx.resample("D")["Amount"].sum()

OrderDate
2026-01-05    1500
2026-01-06       0
2026-01-07    2500
2026-01-08     800
2026-01-09       0
              ...
2026-03-08       0
2026-03-09       0
2026-03-10    2600
2026-03-11       0
2026-03-12    3700
Freq: D, Name: Amount, Length: 67, dtype: int64

## mini-project

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [7]:

# 1️⃣ Create a dataset of website visits (string dates + visit counts)

# 2️⃣ Convert VisitDate to datetime
# Write your code here

# 3️⃣ Set VisitDate as the index
# Write your code here

# 4️⃣ Resample to get total visitors per month
# Write your code here

# 5️⃣ Resample to get average visitors per week
# Write your code here

In [15]:
data = {
    "Date": [
        "2026-01-01",
        "2026-01-03",
        "2026-01-05",
        "2026-01-08",
        "2026-01-10",
        "2026-01-13",
        "2026-01-15",
        "2026-01-18",
        "2026-01-20",
        "2026-01-23",
        "2026-01-25",
        "2026-01-28",
        "2026-02-01",
        "2026-02-04",
        "2026-02-07",
        "2026-02-10",
        "2026-02-14",
        "2026-02-18",
        "2026-02-22",
        "2026-02-25"
    ],
    "Visits": [
        120, 185, 150, 230, 195,
        275, 310, 260, 340, 295,
        380, 410, 365, 450, 420,
        490, 530, 475, 560, 610
    ]
}

df = pd.DataFrame(data)

print(df)

          Date  Visits
0   2026-01-01     120
1   2026-01-03     185
2   2026-01-05     150
3   2026-01-08     230
4   2026-01-10     195
5   2026-01-13     275
6   2026-01-15     310
7   2026-01-18     260
8   2026-01-20     340
9   2026-01-23     295
10  2026-01-25     380
11  2026-01-28     410
12  2026-02-01     365
13  2026-02-04     450
14  2026-02-07     420
15  2026-02-10     490
16  2026-02-14     530
17  2026-02-18     475
18  2026-02-22     560
19  2026-02-25     610

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.

In [16]:
df["Date"]=pd.to_datetime(df["Date"])

In [ ]:
df_idx=df.set_index("Date")

In [18]:
df_idx

            Visits
Date
2026-01-01     120
2026-01-03     185
2026-01-05     150
2026-01-08     230
2026-01-10     195
2026-01-13     275
2026-01-15     310
2026-01-18     260
2026-01-20     340
2026-01-23     295
2026-01-25     380
2026-01-28     410
2026-02-01     365
2026-02-04     450
2026-02-07     420
2026-02-10     490
2026-02-14     530
2026-02-18     475
2026-02-22     560
2026-02-25     610

In [19]:
df_idx.resample("ME")["Visits"].sum()

Date
2026-01-31    3150
2026-02-28    3900
Freq: ME, Name: Visits, dtype: int64

In [21]:
df_idx.resample("W")["Visits"].mean()

Date
2026-01-04    152.500000
2026-01-11    191.666667
2026-01-18    281.666667
2026-01-25    338.333333
2026-02-01    387.500000
2026-02-08    435.000000
2026-02-15    510.000000
2026-02-22    517.500000
2026-03-01    610.000000
Freq: W-SUN, Name: Visits, dtype: float64