# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [26]:
import pandas as pd
from rich import print

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:

  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [27]:
df["Department"].value_counts()

Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

In [28]:
df[df["Department"]=="IT"]["Salary"].mean()

np.float64(72333.33333333333)

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [29]:
objs=df.groupby("Department")
for obj in objs:
    print(obj)

(
    'Finance',
      Employee Department  Salary
3     Anna    Finance   65000
4      Tom    Finance   60000
7     Kate    Finance   58000
)

('HR',   Employee Department  Salary
0     John         HR   50000
5    Laura         HR   52000)

(
    'IT',
      Employee Department  Salary
1    Sarah         IT   70000
2     Mike         IT   72000
6    Steve         IT   75000
)

In [30]:
objs=df.groupby("Department")["Salary"]
for obj in objs:
    print(obj)

('Finance', 3    65000
4    60000
7    58000
Name: Salary, dtype: int64)

('HR', 0    50000
5    52000
Name: Salary, dtype: int64)

('IT', 1    70000
2    72000
6    75000
Name: Salary, dtype: int64)

In [31]:
df.groupby("Department")["Salary"].agg(func="mean")

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

In [32]:
df.groupby("Department")["Employee"].count()

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [33]:
df.groupby("Department").agg(mean_Salary=("Salary","mean"),median_salary=("Salary","median"),max_salary=("Salary","max"))

             mean_Salary  median_salary  max_salary
Department
Finance     61000.000000        60000.0       65000
HR          51000.000000        51000.0       52000
IT          72333.333333        72000.0       75000

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [34]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:

  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [35]:
df_temp=df.groupby(["Department"]).agg({
    "Salary":["mean","max","min"],
    "Age":["std","median","mean"]
})
print(df_temp)

                  Salary                     Age
                    mean    max    min       std median       mean
Department
Finance     61000.000000  65000  58000  4.932883   27.0  29.333333
HR          51000.000000  52000  50000  0.707107   28.5  28.500000
IT          72333.333333  75000  70000  1.000000   31.0  31.000000

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [39]:
df.pivot_table(values=["Salary","Age"],index="Department",aggfunc="mean")

                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          28.500000  51000.000000
IT          31.000000  72333.333333

In [40]:
import seaborn as sns
df=sns.load_dataset("flights")
df

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [41]:
df["year"].value_counts()

year
1949    12
1950    12
1951    12
1952    12
1953    12
1954    12
1955    12
1956    12
1957    12
1958    12
1959    12
1960    12
Name: count, dtype: int64

In [47]:
df.pivot_table(values="passengers",index="year",columns="month",aggfunc="median")

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

In [48]:
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:

  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [50]:
df["AgeGroup"]=pd.cut(df["Age"],bins=[25,30,35,40],labels=["25-30","31-35","36-40"])
df["AgeGroup"]

0    25-30
1    31-35
2    25-30
3    25-30
4    31-35
5    25-30
6    31-35
7    25-30
Name: AgeGroup, dtype: category
Categories (3, str): ['25-30' < '31-35' < '36-40']

In [51]:
print(df)

  Employee Department  Salary  Age AgeGroup
0     John         HR   50000   28    25-30
1    Sarah         IT   70000   32    31-35
2     Mike         IT   72000   30    25-30
3     Anna    Finance   65000   27    25-30
4      Tom    Finance   60000   35    31-35
5    Laura         HR   52000   29    25-30
6    Steve         IT   75000   31    31-35
7     Kate    Finance   58000   26    25-30

In [52]:
pd.crosstab(df["Department"],df["AgeGroup"])

AgeGroup    25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

- THE PIVOT TABLE IS AGGREGRATIONAL 
- THE CROSSTAB IS CATEGORIAL

In [36]:
# df["AgeGroup"] = pd.cut(df["Age"], bins=[25, 30, 35, 40], labels=["25-30", "31-35", "36-40"])
# crosstab_result = pd.crosstab(df["Department"], df["AgeGroup"])
# df

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [37]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City

# 2. Group by Department to get average Salary and max Age
# Write your code here

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here

# 5. Build a crosstab for Department vs City
# Write your code here

In [53]:

data = {
    "Department": [
        "IT", "HR", "Finance", "IT", "Marketing",
        "Sales", "HR", "IT", "Finance", "Sales",
        "Marketing", "IT", "HR", "Finance", "Sales",
        "IT", "Marketing", "Finance", "HR", "IT",
        "Sales", "Finance", "Marketing", "IT", "HR",
        "Sales", "IT", "Finance", "Marketing", "HR"
    ],

    "Employee": [
        "Ram", "Sita", "Hari", "Ramesh", "Amit",
        "Sunil", "Nisha", "Bikash", "Raj", "Kiran",
        "Puja", "Anil", "Suman", "Ravi", "Rohan",
        "Ashish", "Mina", "Prakash", "Gita", "Roshan",
        "Nabin", "Deepak", "Pooja", "Manish", "Sarita",
        "Sagar", "Bimal", "Arjun", "Anita", "Kamal"
    ],

    "Salary": [
        65000, 45000, 58000, 72000, 52000,
        48000, 47000, 80000, 62000, 50000,
        55000, 68000, 49000, 65000, 53000,
        85000, 57000, 70000, 51000, 75000,
        56000, 64000, 59000, 78000, 46000,
        54000, 69000, 61000, 53000, 48000
    ],

    "Age": [
        25, 28, 32, 27, 30,
        26, 29, 31, 35, 24,
        27, 33, 26, 38, 29,
        34, 25, 36, 30, 28,
        31, 37, 26, 32, 29,
        27, 35, 33, 24, 30
    ],

    "City": [
        "Kathmandu", "Pokhara", "Lalitpur", "Kathmandu", "Bhaktapur",
        "Pokhara", "Kathmandu", "Lalitpur", "Biratnagar", "Kathmandu",
        "Pokhara", "Bhaktapur", "Lalitpur", "Kathmandu", "Pokhara",
        "Kathmandu", "Biratnagar", "Lalitpur", "Bhaktapur", "Kathmandu",
        "Pokhara", "Lalitpur", "Kathmandu", "Biratnagar", "Pokhara",
        "Kathmandu", "Bhaktapur", "Lalitpur", "Kathmandu", "Pokhara"
    ]
}

df = pd.DataFrame(data)

print(df)

   Department Employee  Salary  Age        City
0          IT      Ram   65000   25   Kathmandu
1          HR     Sita   45000   28     Pokhara
2     Finance     Hari   58000   32    Lalitpur
3          IT   Ramesh   72000   27   Kathmandu
4   Marketing     Amit   52000   30   Bhaktapur
5       Sales    Sunil   48000   26     Pokhara
6          HR    Nisha   47000   29   Kathmandu
7          IT   Bikash   80000   31    Lalitpur
8     Finance      Raj   62000   35  Biratnagar
9       Sales    Kiran   50000   24   Kathmandu
10  Marketing     Puja   55000   27     Pokhara
11         IT     Anil   68000   33   Bhaktapur
12         HR    Suman   49000   26    Lalitpur
13    Finance     Ravi   65000   38   Kathmandu
14      Sales    Rohan   53000   29     Pokhara
15         IT   Ashish   85000   34   Kathmandu
16  Marketing     Mina   57000   25  Biratnagar
17    Finance  Prakash   70000   36    Lalitpur
18         HR     Gita   51000   30   Bhaktapur
19         IT   Roshan   75000   28   Kathmandu
20      Sales    Nabin   56000   31     Pokhara
21    Finance   Deepak   64000   37    Lalitpur
22  Marketing    Pooja   59000   26   Kathmandu
23         IT   Manish   78000   32  Biratnagar
24         HR   Sarita   46000   29     Pokhara
25      Sales    Sagar   54000   27   Kathmandu
26         IT    Bimal   69000   35   Bhaktapur
27    Finance    Arjun   61000   33    Lalitpur
28  Marketing    Anita   53000   24   Kathmandu
29         HR    Kamal   48000   30     Pokhara

In [55]:
df.groupby("Department").agg(average_salary=("Salary","mean"),max_salary=("Salary","mean"))

            average_salary    max_salary
Department
Finance       63333.333333  63333.333333
HR            47666.666667  47666.666667
IT            74000.000000  74000.000000
Marketing     55200.000000  55200.000000
Sales         52200.000000  52200.000000

In [56]:
df.groupby("Department").agg({"Salary":"mean","Age":"max"})

                  Salary  Age
Department
Finance     63333.333333   38
HR          47666.666667   30
IT          74000.000000   35
Marketing   55200.000000   30
Sales       52200.000000   31

In [57]:
df.pivot_table(values="Salary",index="Department",columns="City",aggfunc="mean")

City        Bhaktapur  Biratnagar  Kathmandu  Lalitpur       Pokhara
Department
Finance           NaN     62000.0    65000.0   63250.0           NaN
HR            51000.0         NaN    47000.0   49000.0  46333.333333
IT            68500.0     78000.0    74250.0   80000.0           NaN
Marketing     52000.0     57000.0    56000.0       NaN  55000.000000
Sales             NaN         NaN    52000.0       NaN  52333.333333

In [58]:
pd.crosstab(df["Department"],df["City"])

City        Bhaktapur  Biratnagar  Kathmandu  Lalitpur  Pokhara
Department
Finance             0           1          1         4        0
HR                  1           0          1         1        3
IT                  2           1          4         1        0
Marketing           1           1          2         0        1
Sales               0           0          2         0        3

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.