# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [23]:
import pandas as pd
import numpy as np

In [24]:
data = {
    "Name": ["Ram", "Shyam", "Hari", "Sita", "Gita",
             "Mohan", "Rita", "Kiran", "Anil", "Sunita"],
    "Age": [20, 21, 19, 22, 20, 23, 21, 19, 22, 20],
    "Score": [85, 78, 92, 88, 95, 76, 89, 91, 83, 87]
}

df=pd.DataFrame(data)
df

     Name  Age  Score
0     Ram   20     85
1   Shyam   21     78
2    Hari   19     92
3    Sita   22     88
4    Gita   20     95
5   Mohan   23     76
6    Rita   21     89
7   Kiran   19     91
8    Anil   22     83
9  Sunita   20     87

In [25]:
condition=df["Age"]>20
condition

0    False
1     True
2    False
3     True
4    False
5     True
6     True
7    False
8     True
9    False
Name: Age, dtype: bool

In [26]:
df[condition]

    Name  Age  Score
1  Shyam   21     78
3   Sita   22     88
5  Mohan   23     76
6   Rita   21     89
8   Anil   22     83

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [27]:
condition=(df["Age"]>20)&(df["Score"]>85)
condition

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool

In [28]:
df[condition]

   Name  Age  Score
3  Sita   22     88
6  Rita   21     89

In [29]:
condition=(df["Age"]<20)|(df["Score"]>90)
df[condition]

    Name  Age  Score
2   Hari   19     92
4   Gita   20     95
7  Kiran   19     91

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [30]:
df

     Name  Age  Score
0     Ram   20     85
1   Shyam   21     78
2    Hari   19     92
3    Sita   22     88
4    Gita   20     95
5   Mohan   23     76
6    Rita   21     89
7   Kiran   19     91
8    Anil   22     83
9  Sunita   20     87

In [31]:
df.query("Age > 20")

    Name  Age  Score
1  Shyam   21     78
3   Sita   22     88
5  Mohan   23     76
6   Rita   21     89
8   Anil   22     83

In [32]:
df.query("Age > 20 and Score >=85")

   Name  Age  Score
3  Sita   22     88
6  Rita   21     89

In [33]:
hold=20
df.query("Age > @hold")

    Name  Age  Score
1  Shyam   21     78
3   Sita   22     88
5  Mohan   23     76
6   Rita   21     89
8   Anil   22     83

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [34]:
df

     Name  Age  Score
0     Ram   20     85
1   Shyam   21     78
2    Hari   19     92
3    Sita   22     88
4    Gita   20     95
5   Mohan   23     76
6    Rita   21     89
7   Kiran   19     91
8    Anil   22     83
9  Sunita   20     87

In [35]:
df["Name"].str.lower()

0       ram
1     shyam
2      hari
3      sita
4      gita
5     mohan
6      rita
7     kiran
8      anil
9    sunita
Name: Name, dtype: str

In [39]:
df

     Name  Age  Score
0     Ram   20     85
1   Shyam   21     78
2    Hari   19     92
3    Sita   22     88
4    Gita   20     95
5   Mohan   23     76
6    Rita   21     89
7   Kiran   19     91
8    Anil   22     83
9  Sunita   20     87

In [41]:
df["Name"].str.contains("a",case=True)

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8    False
9     True
Name: Name, dtype: bool

In [42]:
df["Name"].str.contains("a",case=False)

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: Name, dtype: bool

In [43]:
df["Name"].str.replace("a","e")

0       Rem
1     Shyem
2      Heri
3      Site
4      Gite
5     Mohen
6      Rite
7     Kiren
8      Anil
9    Sunite
Name: Name, dtype: str

In [45]:
df

     Name  Age  Score
0     Ram   20     85
1   Shyam   21     78
2    Hari   19     92
3    Sita   22     88
4    Gita   20     95
5   Mohan   23     76
6    Rita   21     89
7   Kiran   19     91
8    Anil   22     83
9  Sunita   20     87

In [47]:
condition=df["Name"].str.startswith("A")
condition

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: Name, dtype: bool

In [48]:
df[condition]

   Name  Age  Score
8  Anil   22     83

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [36]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.

In [54]:
data = {
    "Name": ["Ram", "Shyam", "Hari", "Sita", "Gita",
             "Mohan", "Rita", "Kiran", "Anil", "Sunita"],
    "Age": [50, 31, 19, 22, 40, 23, 51, 29, 32, 20],
    "City": ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Chitwan",
             "Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Butwal"],
    "Score": [85, 78, 92, 88, 95, 76, 89, 91, 83, 87]
}

df = pd.DataFrame(data)
df

     Name  Age        City  Score
0     Ram   50   Kathmandu     85
1   Shyam   31     Pokhara     78
2    Hari   19    Lalitpur     92
3    Sita   22   Bhaktapur     88
4    Gita   40     Chitwan     95
5   Mohan   23   Kathmandu     76
6    Rita   51     Pokhara     89
7   Kiran   29    Lalitpur     91
8    Anil   32  Biratnagar     83
9  Sunita   20      Butwal     87

In [55]:
df[df["Age"]>25]

    Name  Age        City  Score
0    Ram   50   Kathmandu     85
1  Shyam   31     Pokhara     78
4   Gita   40     Chitwan     95
6   Rita   51     Pokhara     89
7  Kiran   29    Lalitpur     91
8   Anil   32  Biratnagar     83

In [56]:
df[(df["City"]=="Kathmandu")|(df["City"]=="Chitwan")]

    Name  Age       City  Score
0    Ram   50  Kathmandu     85
4   Gita   40    Chitwan     95
5  Mohan   23  Kathmandu     76

In [57]:
df.query("Score >= 85 and Age<35")

     Name  Age       City  Score
2    Hari   19   Lalitpur     92
3    Sita   22  Bhaktapur     88
7   Kiran   29   Lalitpur     91
9  Sunita   20     Butwal     87

In [58]:
df["City"]=df["City"].str.lower()
df["City"]

0     kathmandu
1       pokhara
2      lalitpur
3     bhaktapur
4       chitwan
5     kathmandu
6       pokhara
7      lalitpur
8    biratnagar
9        butwal
Name: City, dtype: str

In [59]:
df["City"].replace("kathmandu","ktm")

0           ktm
1       pokhara
2      lalitpur
3     bhaktapur
4       chitwan
5           ktm
6       pokhara
7      lalitpur
8    biratnagar
9        butwal
Name: City, dtype: str