In [4]:
import pandas as pd
import numpy as np
data = {
    "Product": [
        "Laptop", "Smartphone", "Tablet", "Headphones", "Keyboard",
        "Mouse", "Monitor", "Webcam", "Printer", "Speaker",
        "Smartwatch", "Power Bank", "USB Cable", "Charger", "Hard Drive",
        "SSD", "Graphics Card", "RAM", "Router", "Microphone",
        "Gaming Chair", "Desk Lamp", "External SSD", "Earbuds",
        "Bluetooth Speaker", "Mechanical Keyboard", "Gaming Mouse",
        "Laptop Stand", "Phone Stand", "HDMI Cable"
    ],

    "Price": [
        85000, 55000, 32000, 8500, 4500,
        2500, 28000, 6500, 18000, 7500,
        12000, 4500, 800, 2500, 15000,
        18000, 75000, 6500, 5500, 9500,
        22000, 3500, 20000, 6500, 5500,
        7000, 4500, 3000, 1200, 1800
    ],

    "Stock": [
        25, 40, 18, 65, 90,
        120, 30, 45, 20, 55,
        35, 80, 200, 75, 28,
        42, 12, 60, 50, 25,
        15, 70, 35, 85, 45,
        30, 95, 55, 110, 100
    ],

    "Rating": [
        4.7, 4.6, 4.4, 4.5, 4.3,
        4.2, 4.6, 4.1, 4.0, 4.5,
        4.4, 4.2, 4.3, 4.6, 4.5,
        4.8, 4.7, 4.4, 4.1, 4.6,
        4.5, 4.0, 4.8, 4.4, 4.3,
        4.6, 4.5, 4.2, 4.1, 4.3
    ]
}

df = pd.DataFrame(data)

print(df)

                Product  Price  Stock  Rating
0                Laptop  85000     25     4.7
1            Smartphone  55000     40     4.6
2                Tablet  32000     18     4.4
3            Headphones   8500     65     4.5
4              Keyboard   4500     90     4.3
5                 Mouse   2500    120     4.2
6               Monitor  28000     30     4.6
7                Webcam   6500     45     4.1
8               Printer  18000     20     4.0
9               Speaker   7500     55     4.5
10           Smartwatch  12000     35     4.4
11           Power Bank   4500     80     4.2
12            USB Cable    800    200     4.3
13              Charger   2500     75     4.6
14           Hard Drive  15000     28     4.5
15                  SSD  18000     42     4.8
16        Graphics Card  75000     12     4.7
17                  RAM   6500     60     4.4
18               Router   5500     50     4.1
19           Microphone   9500     25     4.6
20         Gaming Chair  22000     15     4.5
21            Desk Lamp   3500     70     4.0
22         External SSD  20000     35     4.8
23              Earbuds   6500     85     4.4
24    Bluetooth Speaker   5500     45     4.3
25  Mechanical Keyboard   7000     30     4.6
26         Gaming Mouse   4500     95     4.5
27         Laptop Stand   3000     55     4.2
28          Phone Stand   1200    110     4.1
29           HDMI Cable   1800    100     4.3

# 🐼 Pandas - Class 5: Sorting & Basic Statistics
Welcome to **Class 5** of our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [6]:
df.sort_values(by="Price",ascending=False)

                Product  Price  Stock  Rating
0                Laptop  85000     25     4.7
16        Graphics Card  75000     12     4.7
1            Smartphone  55000     40     4.6
2                Tablet  32000     18     4.4
6               Monitor  28000     30     4.6
20         Gaming Chair  22000     15     4.5
22         External SSD  20000     35     4.8
15                  SSD  18000     42     4.8
8               Printer  18000     20     4.0
14           Hard Drive  15000     28     4.5
10           Smartwatch  12000     35     4.4
19           Microphone   9500     25     4.6
3            Headphones   8500     65     4.5
9               Speaker   7500     55     4.5
25  Mechanical Keyboard   7000     30     4.6
7                Webcam   6500     45     4.1
23              Earbuds   6500     85     4.4
17                  RAM   6500     60     4.4
24    Bluetooth Speaker   5500     45     4.3
18               Router   5500     50     4.1
4              Keyboard   4500     90     4.3
11           Power Bank   4500     80     4.2
26         Gaming Mouse   4500     95     4.5
21            Desk Lamp   3500     70     4.0
27         Laptop Stand   3000     55     4.2
5                 Mouse   2500    120     4.2
13              Charger   2500     75     4.6
29           HDMI Cable   1800    100     4.3
28          Phone Stand   1200    110     4.1
12            USB Cable    800    200     4.3

In [7]:
df.sort_values(by=["Price","Stock"],ascending=[True,False])

                Product  Price  Stock  Rating
12            USB Cable    800    200     4.3
28          Phone Stand   1200    110     4.1
29           HDMI Cable   1800    100     4.3
5                 Mouse   2500    120     4.2
13              Charger   2500     75     4.6
27         Laptop Stand   3000     55     4.2
21            Desk Lamp   3500     70     4.0
26         Gaming Mouse   4500     95     4.5
4              Keyboard   4500     90     4.3
11           Power Bank   4500     80     4.2
18               Router   5500     50     4.1
24    Bluetooth Speaker   5500     45     4.3
23              Earbuds   6500     85     4.4
17                  RAM   6500     60     4.4
7                Webcam   6500     45     4.1
25  Mechanical Keyboard   7000     30     4.6
9               Speaker   7500     55     4.5
3            Headphones   8500     65     4.5
19           Microphone   9500     25     4.6
10           Smartwatch  12000     35     4.4
14           Hard Drive  15000     28     4.5
15                  SSD  18000     42     4.8
8               Printer  18000     20     4.0
22         External SSD  20000     35     4.8
20         Gaming Chair  22000     15     4.5
6               Monitor  28000     30     4.6
2                Tablet  32000     18     4.4
1            Smartphone  55000     40     4.6
16        Graphics Card  75000     12     4.7
0                Laptop  85000     25     4.7

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [8]:
df.mean(numeric_only=True)

Price     15726.666667
Stock        58.500000
Rating        4.406667
dtype: float64

In [9]:
df.median(numeric_only=True)

Price     6750.0
Stock       47.5
Rating       4.4
dtype: float64

In [10]:
df.mode(numeric_only=True)

    Price  Stock  Rating
0  4500.0     25     4.5
1  6500.0     30     4.6
2     NaN     35     NaN
3     NaN     45     NaN
4     NaN     55     NaN

In [11]:
df.std(numeric_only=True)

Price     20942.432315
Stock        39.945437
Rating        0.227328
dtype: float64

In [12]:
df.describe()

              Price       Stock     Rating
count     30.000000   30.000000  30.000000
mean   15726.666667   58.500000   4.406667
std    20942.432315   39.945437   0.227328
min      800.000000   12.000000   4.000000
25%     4500.000000   30.000000   4.225000
50%     6750.000000   47.500000   4.400000
75%    18000.000000   78.750000   4.600000
max    85000.000000  200.000000   4.800000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [ ]:
df["Product"].value_counts(normalize=True)#SHOWS IN THE TERM OF PERCENTAGE

Product
Laptop                 0.033333
Smartphone             0.033333
Tablet                 0.033333
Headphones             0.033333
Keyboard               0.033333
Mouse                  0.033333
Monitor                0.033333
Webcam                 0.033333
Printer                0.033333
Speaker                0.033333
Smartwatch             0.033333
Power Bank             0.033333
USB Cable              0.033333
Charger                0.033333
Hard Drive             0.033333
SSD                    0.033333
Graphics Card          0.033333
RAM                    0.033333
Router                 0.033333
Microphone             0.033333
Gaming Chair           0.033333
Desk Lamp              0.033333
External SSD           0.033333
Earbuds                0.033333
Bluetooth Speaker      0.033333
Mechanical Keyboard    0.033333
Gaming Mouse           0.033333
Laptop Stand           0.033333
Phone Stand            0.033333
HDMI Cable             0.033333
Name: proportion, dtype: float64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [16]:
df.corr(numeric_only=True)

           Price     Stock    Rating
Price   1.000000 -0.504586  0.509800
Stock  -0.504586  1.000000 -0.364546
Rating  0.509800 -0.364546  1.000000

In [17]:
df.cov(numeric_only=True)

               Price          Stock       Rating
Price   4.385855e+08 -422113.793103  2427.057471
Stock  -4.221138e+05    1595.637931    -3.310345
Rating  2.427057e+03      -3.310345     0.051678

In [18]:
df["Price"].corr(df["Rating"])

np.float64(0.5097995113084861)

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [ ]:
# Write your mini practice solution here

# 1. Build a DataFrame with columns: Name, Age, Score, Height

# 2. Sort the data by Score (descending)
# Write your code here

# 3. Get mean, median, mode, and std of numeric columns
# Write your code here

# 4. Use value_counts on Name or any categorical column
# Write your code here

# 5. Compute corr() and cov() for all numeric columns
# Write your code here

In [19]:
data = {
    "Name": [
        "Ram", "Ramesh", "Ramesh", "Sita", "Sita",
        "Hari", "Harish", "Bikash", "Bikram", "Bikash",
        "Amit", "Amita", "Anil", "Sunil", "Sunita",
        "Raj", "Rajan", "Ravi", "Ravi", "Kiran",
        "Kiran", "Nisha", "Nisha", "Puja", "Pooja",
        "Suman", "Suman", "Roshan", "Rohan", "Rohan"
    ],
    "Age": [
        20, 21, 22, 19, 20,
        21, 23, 20, 22, 21,
        19, 20, 21, 22, 20,
        23, 21, 20, 22, 19,
        21, 20, 22, 19, 21,
        23, 20, 22, 21, 23
    ],
    "Score": [
        85, 78, 92, 88, 75,
        81, 69, 95, 73, 87,
        90, 82, 76, 89, 94,
        68, 91, 84, 79, 88,
        72, 96, 83, 77, 86,
        70, 93, 80, 74, 90
    ],
    "Height": [
        170, 175, 168, 160, 162,
        172, 178, 169, 180, 171,
        174, 158, 176, 173, 161,
        182, 177, 170, 172, 165,
        168, 159, 163, 157, 164,
        179, 171, 181, 176, 174
    ]
}

df = pd.DataFrame(data)

print(df)

      Name  Age  Score  Height
0      Ram   20     85     170
1   Ramesh   21     78     175
2   Ramesh   22     92     168
3     Sita   19     88     160
4     Sita   20     75     162
5     Hari   21     81     172
6   Harish   23     69     178
7   Bikash   20     95     169
8   Bikram   22     73     180
9   Bikash   21     87     171
10    Amit   19     90     174
11   Amita   20     82     158
12    Anil   21     76     176
13   Sunil   22     89     173
14  Sunita   20     94     161
15     Raj   23     68     182
16   Rajan   21     91     177
17    Ravi   20     84     170
18    Ravi   22     79     172
19   Kiran   19     88     165
20   Kiran   21     72     168
21   Nisha   20     96     159
22   Nisha   22     83     163
23    Puja   19     77     157
24   Pooja   21     86     164
25   Suman   23     70     179
26   Suman   20     93     171
27  Roshan   22     80     181
28   Rohan   21     74     176
29   Rohan   23     90     174

In [20]:
df.sort_values(by="Score",ascending=False)

      Name  Age  Score  Height
21   Nisha   20     96     159
7   Bikash   20     95     169
14  Sunita   20     94     161
26   Suman   20     93     171
2   Ramesh   22     92     168
16   Rajan   21     91     177
10    Amit   19     90     174
29   Rohan   23     90     174
13   Sunil   22     89     173
19   Kiran   19     88     165
3     Sita   19     88     160
9   Bikash   21     87     171
24   Pooja   21     86     164
0      Ram   20     85     170
17    Ravi   20     84     170
22   Nisha   22     83     163
11   Amita   20     82     158
5     Hari   21     81     172
27  Roshan   22     80     181
18    Ravi   22     79     172
1   Ramesh   21     78     175
23    Puja   19     77     157
12    Anil   21     76     176
4     Sita   20     75     162
28   Rohan   21     74     176
8   Bikram   22     73     180
20   Kiran   21     72     168
25   Suman   23     70     179
6   Harish   23     69     178
15     Raj   23     68     182

In [22]:
print(df.mean(numeric_only=True),"\n")
print(df.median(numeric_only=True),"\n")
print(df.mode(numeric_only=True),"\n")
print(df.std(numeric_only=True),"\n")

Age        20.933333
Score      82.833333
Height    170.166667
dtype: float64

Age        21.0
Score      83.5
Height    171.0
dtype: float64

    Age  Score  Height
0  20.0   88.0     168
1  21.0   90.0     170
2   NaN    NaN     171
3   NaN    NaN     172
4   NaN    NaN     174
5   NaN    NaN     176

Age       1.257620
Score     8.279944
Height    7.201931
dtype: float64

In [23]:
df["Name"].value_counts()

Name
Ramesh    2
Sita      2
Bikash    2
Ravi      2
Kiran     2
Nisha     2
Suman     2
Rohan     2
Ram       1
Hari      1
Harish    1
Bikram    1
Amit      1
Amita     1
Anil      1
Sunil     1
Sunita    1
Raj       1
Rajan     1
Puja      1
Pooja     1
Roshan    1
Name: count, dtype: int64

In [24]:
df.corr(numeric_only=True)

             Age     Score    Height
Age     1.000000 -0.444845  0.652297
Score  -0.444845  1.000000 -0.415868
Height  0.652297 -0.415868  1.000000

In [25]:
df.cov(numeric_only=True)

             Age      Score     Height
Age     1.581609  -4.632184   5.908046
Score  -4.632184  68.557471 -24.798851
Height  5.908046 -24.798851  51.867816

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.