# 🐼 Pandas - Class 7: Merging, Joining & Concatenation
Welcome to **Class 7** of our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

In [35]:
import pandas as pd
from rich import print

df1 = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Ram", "Sita", "Hari", "Ramesh", "Amit",
             "Nisha", "Bikash", "Puja", "Kiran", "Suman"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales",
                    "HR", "IT", "Marketing", "Finance", "Sales"],
    "Salary": [60000, 45000, 55000, 70000, 48000,
               47000, 75000, 52000, 58000, 50000]
})
print(df1)

df2 = pd.DataFrame({
    "Employee_ID": [105, 106, 107, 108, 109, 110, 111, 112, 113, 114],
    "Age": [25, 29, 31, 24, 35, 28, 30, 26, 33, 27],
    "City": ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Kathmandu",
             "Pokhara", "Biratnagar", "Lalitpur", "Kathmandu", "Pokhara"],
    "Experience": [2, 4, 6, 1, 8, 3, 5, 2, 7, 4]
})
print(df2)

df3 = pd.DataFrame({
    "Score": [85, 78, 92, 88, 76, 90, 84, 95, 72, 89],
    "Rating": [4.2, 3.8, 4.7, 4.5, 3.6, 4.6, 4.1, 4.9, 3.5, 4.4]
})

print(df3)

   Employee_ID    Name Department  Salary
0          101     Ram         IT   60000
1          102    Sita         HR   45000
2          103    Hari    Finance   55000
3          104  Ramesh         IT   70000
4          105    Amit      Sales   48000
5          106   Nisha         HR   47000
6          107  Bikash         IT   75000
7          108    Puja  Marketing   52000
8          109   Kiran    Finance   58000
9          110   Suman      Sales   50000

   Employee_ID  Age        City  Experience
0          105   25   Kathmandu           2
1          106   29     Pokhara           4
2          107   31    Lalitpur           6
3          108   24   Bhaktapur           1
4          109   35   Kathmandu           8
5          110   28     Pokhara           3
6          111   30  Biratnagar           5
7          112   26    Lalitpur           2
8          113   33   Kathmandu           7
9          114   27     Pokhara           4

   Score  Rating
0     85     4.2
1     78     3.8
2     92     4.7
3     88     4.5
4     76     3.6
5     90     4.6
6     84     4.1
7     95     4.9
8     72     3.5
9     89     4.4

## 1. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

In [36]:

# Dataset 1: Product details


# Dataset 2: More products (same columns as df1 → good for vertical stacking)

# Dataset 3: Additional info (different columns → good for horizontal stacking)

In [37]:
pd.concat([df1,df2])

   Employee_ID    Name Department   Salary   Age        City  Experience
0          101     Ram         IT  60000.0   NaN         NaN         NaN
1          102    Sita         HR  45000.0   NaN         NaN         NaN
2          103    Hari    Finance  55000.0   NaN         NaN         NaN
3          104  Ramesh         IT  70000.0   NaN         NaN         NaN
4          105    Amit      Sales  48000.0   NaN         NaN         NaN
5          106   Nisha         HR  47000.0   NaN         NaN         NaN
6          107  Bikash         IT  75000.0   NaN         NaN         NaN
7          108    Puja  Marketing  52000.0   NaN         NaN         NaN
8          109   Kiran    Finance  58000.0   NaN         NaN         NaN
9          110   Suman      Sales  50000.0   NaN         NaN         NaN
0          105     NaN        NaN      NaN  25.0   Kathmandu         2.0
1          106     NaN        NaN      NaN  29.0     Pokhara         4.0
2          107     NaN        NaN      NaN  31.0    Lalitpur         6.0
3          108     NaN        NaN      NaN  24.0   Bhaktapur         1.0
4          109     NaN        NaN      NaN  35.0   Kathmandu         8.0
5          110     NaN        NaN      NaN  28.0     Pokhara         3.0
6          111     NaN        NaN      NaN  30.0  Biratnagar         5.0
7          112     NaN        NaN      NaN  26.0    Lalitpur         2.0
8          113     NaN        NaN      NaN  33.0   Kathmandu         7.0
9          114     NaN        NaN      NaN  27.0     Pokhara         4.0

In [38]:
pd.concat([df1,df2],ignore_index=True)

    Employee_ID    Name Department   Salary   Age        City  Experience
0           101     Ram         IT  60000.0   NaN         NaN         NaN
1           102    Sita         HR  45000.0   NaN         NaN         NaN
2           103    Hari    Finance  55000.0   NaN         NaN         NaN
3           104  Ramesh         IT  70000.0   NaN         NaN         NaN
4           105    Amit      Sales  48000.0   NaN         NaN         NaN
5           106   Nisha         HR  47000.0   NaN         NaN         NaN
6           107  Bikash         IT  75000.0   NaN         NaN         NaN
7           108    Puja  Marketing  52000.0   NaN         NaN         NaN
8           109   Kiran    Finance  58000.0   NaN         NaN         NaN
9           110   Suman      Sales  50000.0   NaN         NaN         NaN
10          105     NaN        NaN      NaN  25.0   Kathmandu         2.0
11          106     NaN        NaN      NaN  29.0     Pokhara         4.0
12          107     NaN        NaN      NaN  31.0    Lalitpur         6.0
13          108     NaN        NaN      NaN  24.0   Bhaktapur         1.0
14          109     NaN        NaN      NaN  35.0   Kathmandu         8.0
15          110     NaN        NaN      NaN  28.0     Pokhara         3.0
16          111     NaN        NaN      NaN  30.0  Biratnagar         5.0
17          112     NaN        NaN      NaN  26.0    Lalitpur         2.0
18          113     NaN        NaN      NaN  33.0   Kathmandu         7.0
19          114     NaN        NaN      NaN  27.0     Pokhara         4.0

In [39]:
pd.concat([df1,df3])

   Employee_ID    Name Department   Salary  Score  Rating
0        101.0     Ram         IT  60000.0    NaN     NaN
1        102.0    Sita         HR  45000.0    NaN     NaN
2        103.0    Hari    Finance  55000.0    NaN     NaN
3        104.0  Ramesh         IT  70000.0    NaN     NaN
4        105.0    Amit      Sales  48000.0    NaN     NaN
5        106.0   Nisha         HR  47000.0    NaN     NaN
6        107.0  Bikash         IT  75000.0    NaN     NaN
7        108.0    Puja  Marketing  52000.0    NaN     NaN
8        109.0   Kiran    Finance  58000.0    NaN     NaN
9        110.0   Suman      Sales  50000.0    NaN     NaN
0          NaN     NaN        NaN      NaN   85.0     4.2
1          NaN     NaN        NaN      NaN   78.0     3.8
2          NaN     NaN        NaN      NaN   92.0     4.7
3          NaN     NaN        NaN      NaN   88.0     4.5
4          NaN     NaN        NaN      NaN   76.0     3.6
5          NaN     NaN        NaN      NaN   90.0     4.6
6          NaN     NaN        NaN      NaN   84.0     4.1
7          NaN     NaN        NaN      NaN   95.0     4.9
8          NaN     NaN        NaN      NaN   72.0     3.5
9          NaN     NaN        NaN      NaN   89.0     4.4

In [40]:
pd.concat([df1,df3],axis=1)

   Employee_ID    Name Department  Salary  Score  Rating
0          101     Ram         IT   60000     85     4.2
1          102    Sita         HR   45000     78     3.8
2          103    Hari    Finance   55000     92     4.7
3          104  Ramesh         IT   70000     88     4.5
4          105    Amit      Sales   48000     76     3.6
5          106   Nisha         HR   47000     90     4.6
6          107  Bikash         IT   75000     84     4.1
7          108    Puja  Marketing   52000     95     4.9
8          109   Kiran    Finance   58000     72     3.5
9          110   Suman      Sales   50000     89     4.4

## 2. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

In [41]:
pd.merge(df1,df2,on="Employee_ID",how="inner")

   Employee_ID    Name Department  Salary  Age       City  Experience
0          105    Amit      Sales   48000   25  Kathmandu           2
1          106   Nisha         HR   47000   29    Pokhara           4
2          107  Bikash         IT   75000   31   Lalitpur           6
3          108    Puja  Marketing   52000   24  Bhaktapur           1
4          109   Kiran    Finance   58000   35  Kathmandu           8
5          110   Suman      Sales   50000   28    Pokhara           3

In [42]:
pd.merge(df1,df2,on="Employee_ID",how="outer")

    Employee_ID    Name Department   Salary   Age        City  Experience
0           101     Ram         IT  60000.0   NaN         NaN         NaN
1           102    Sita         HR  45000.0   NaN         NaN         NaN
2           103    Hari    Finance  55000.0   NaN         NaN         NaN
3           104  Ramesh         IT  70000.0   NaN         NaN         NaN
4           105    Amit      Sales  48000.0  25.0   Kathmandu         2.0
5           106   Nisha         HR  47000.0  29.0     Pokhara         4.0
6           107  Bikash         IT  75000.0  31.0    Lalitpur         6.0
7           108    Puja  Marketing  52000.0  24.0   Bhaktapur         1.0
8           109   Kiran    Finance  58000.0  35.0   Kathmandu         8.0
9           110   Suman      Sales  50000.0  28.0     Pokhara         3.0
10          111     NaN        NaN      NaN  30.0  Biratnagar         5.0
11          112     NaN        NaN      NaN  26.0    Lalitpur         2.0
12          113     NaN        NaN      NaN  33.0   Kathmandu         7.0
13          114     NaN        NaN      NaN  27.0     Pokhara         4.0

In [43]:
pd.merge(df1,df2,on="Employee_ID",how="left")

   Employee_ID    Name Department  Salary   Age       City  Experience
0          101     Ram         IT   60000   NaN        NaN         NaN
1          102    Sita         HR   45000   NaN        NaN         NaN
2          103    Hari    Finance   55000   NaN        NaN         NaN
3          104  Ramesh         IT   70000   NaN        NaN         NaN
4          105    Amit      Sales   48000  25.0  Kathmandu         2.0
5          106   Nisha         HR   47000  29.0    Pokhara         4.0
6          107  Bikash         IT   75000  31.0   Lalitpur         6.0
7          108    Puja  Marketing   52000  24.0  Bhaktapur         1.0
8          109   Kiran    Finance   58000  35.0  Kathmandu         8.0
9          110   Suman      Sales   50000  28.0    Pokhara         3.0

In [44]:
pd.merge(df1,df2,on="Employee_ID",how="right")

   Employee_ID    Name Department   Salary  Age        City  Experience
0          105    Amit      Sales  48000.0   25   Kathmandu           2
1          106   Nisha         HR  47000.0   29     Pokhara           4
2          107  Bikash         IT  75000.0   31    Lalitpur           6
3          108    Puja  Marketing  52000.0   24   Bhaktapur           1
4          109   Kiran    Finance  58000.0   35   Kathmandu           8
5          110   Suman      Sales  50000.0   28     Pokhara           3
6          111     NaN        NaN      NaN   30  Biratnagar           5
7          112     NaN        NaN      NaN   26    Lalitpur           2
8          113     NaN        NaN      NaN   33   Kathmandu           7
9          114     NaN        NaN      NaN   27     Pokhara           4

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

In [45]:
emp=df1.set_index("Employee_ID")
df3_temp=df3.set_index(emp.index)

In [46]:
emp.join(df3)

               Name Department  Salary  Score  Rating
Employee_ID
101             Ram         IT   60000    NaN     NaN
102            Sita         HR   45000    NaN     NaN
103            Hari    Finance   55000    NaN     NaN
104          Ramesh         IT   70000    NaN     NaN
105            Amit      Sales   48000    NaN     NaN
106           Nisha         HR   47000    NaN     NaN
107          Bikash         IT   75000    NaN     NaN
108            Puja  Marketing   52000    NaN     NaN
109           Kiran    Finance   58000    NaN     NaN
110           Suman      Sales   50000    NaN     NaN

## 4. Practical Examples
- Combine sales and revenue data to see performance.
- Merge students with marks to link records.
- Practice with realistic datasets to understand alignment and missing data handling.

In [47]:
sales = pd.DataFrame({
    "ProductID": [111, 102, 113, 104, 105, 106, 107, 108, 109, 110],
    "UnitsSold": [25, 40, 15, 30, 50, 20, 35, 45, 10, 28]
})

print(sales)

revenue = pd.DataFrame({
    "ProductID": [101, 102, 103, 104, 105, 116, 107, 108, 119, 110],
    "Revenue": [25000, 48000, 18000, 36000, 62500, 22000, 42000, 54000, 12000, 35000]
})

print(revenue)

   ProductID  UnitsSold
0        111         25
1        102         40
2        113         15
3        104         30
4        105         50
5        106         20
6        107         35
7        108         45
8        109         10
9        110         28

   ProductID  Revenue
0        101    25000
1        102    48000
2        103    18000
3        104    36000
4        105    62500
5        116    22000
6        107    42000
7        108    54000
8        119    12000
9        110    35000

In [48]:
merged=pd.merge(sales,revenue,on="ProductID",how="outer")
print(merged)

    ProductID  UnitsSold  Revenue
0         101        NaN  25000.0
1         102       40.0  48000.0
2         103        NaN  18000.0
3         104       30.0  36000.0
4         105       50.0  62500.0
5         106       20.0      NaN
6         107       35.0  42000.0
7         108       45.0  54000.0
8         109       10.0      NaN
9         110       28.0  35000.0
10        111       25.0      NaN
11        113       15.0      NaN
12        116        NaN  22000.0
13        119        NaN  12000.0

## Mini Practice
1. Create three DataFrames: Products, Sales, and Revenue.
2. Concatenate them vertically and horizontally.
3. Merge Sales and Revenue using different join types.
4. Join Products with Sales based on index or a key.
5. Analyze missing values after joins.

In [49]:

# 1. Create three DataFrames: Products, Sales, and Revenue

# 2. Concatenate them vertically and horizontally
# Write your code here

# 3. Merge Sales and Revenue using different join types (inner, left, right, outer)
# Write your code here

# 4. Join Products with Sales based on index or a key
# Write your code here

# 5. Analyze missing values after joins
# Use isna(), info(), or describe() to explore gaps
# Write your code here

---
## Summary
- Used `concat()` for stacking data vertically and horizontally.
- Performed SQL-style joins with `merge()`.
- Applied `join()` with index alignment.
- Explored practical use-cases like sales vs revenue, students vs marks.