# 🐼 Pandas - Class 11: Advanced Tricks & Performance
Welcome to **Class 11** of our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [2]:
import pandas as pd

data = {
    "Name": [
        "Ram", "Sita", "Hari", "Anita", "Bikash",
        "Nisha", "Aayush", "Puja", "Rohan", "Sneha",
        "Kiran", "Amit", "Prabin", "Suman", "Riya",
        "Nabin", "Sarita", "Roshan", "Manish", "Asha"
    ],
    "Math": [
        78, 85, 67, 92, 74,
        88, 95, 81, 69, 90,
        76, 84, 73, 89, 91,
        65, 87, 79, 94, 82
    ],
    "Science": [
        82, 79, 71, 95, 80,
        91, 89, 85, 74, 88,
        81, 86, 77, 92, 94,
        70, 83, 76, 90, 87
    ]
}

df = pd.DataFrame(data)

print(df)

      Name  Math  Science
0      Ram    78       82
1     Sita    85       79
2     Hari    67       71
3    Anita    92       95
4   Bikash    74       80
5    Nisha    88       91
6   Aayush    95       89
7     Puja    81       85
8    Rohan    69       74
9    Sneha    90       88
10   Kiran    76       81
11    Amit    84       86
12  Prabin    73       77
13   Suman    89       92
14    Riya    91       94
15   Nabin    65       70
16  Sarita    87       83
17  Roshan    79       76
18  Manish    94       90
19    Asha    82       87

In [6]:
df["TotalMarks"]=df[["Math","Science"]].apply(lambda row:row.sum(),axis=1)
df

      Name  Math  Science  TotalMarks
0      Ram    78       82         160
1     Sita    85       79         164
2     Hari    67       71         138
3    Anita    92       95         187
4   Bikash    74       80         154
5    Nisha    88       91         179
6   Aayush    95       89         184
7     Puja    81       85         166
8    Rohan    69       74         143
9    Sneha    90       88         178
10   Kiran    76       81         157
11    Amit    84       86         170
12  Prabin    73       77         150
13   Suman    89       92         181
14    Riya    91       94         185
15   Nabin    65       70         135
16  Sarita    87       83         170
17  Roshan    79       76         155
18  Manish    94       90         184
19    Asha    82       87         169

In [7]:
col_mean=df[["Math","Science"]].apply(lambda col:col.mean())
col_mean

Math       81.95
Science    83.50
dtype: float64

In [9]:
def to_grade(s):
    if s>90:
        return "A"
    elif s>80:
        return "B"
    elif s>50:
        return "OK"
    else:
        return "Fail"

In [11]:
df["Math_Grade"]=df["Math"].apply(to_grade)
df

      Name  Math  Science  TotalMarks Math_Grade
0      Ram    78       82         160         OK
1     Sita    85       79         164          B
2     Hari    67       71         138         OK
3    Anita    92       95         187          A
4   Bikash    74       80         154         OK
5    Nisha    88       91         179          B
6   Aayush    95       89         184          A
7     Puja    81       85         166          B
8    Rohan    69       74         143         OK
9    Sneha    90       88         178          B
10   Kiran    76       81         157         OK
11    Amit    84       86         170          B
12  Prabin    73       77         150         OK
13   Suman    89       92         181          B
14    Riya    91       94         185          A
15   Nabin    65       70         135         OK
16  Sarita    87       83         170          B
17  Roshan    79       76         155         OK
18  Manish    94       90         184          A
19    Asha    82       87         169          B

In [12]:
df["Name"]=df["Name"].map(str.lower)
df

      Name  Math  Science  TotalMarks Math_Grade
0      ram    78       82         160         OK
1     sita    85       79         164          B
2     hari    67       71         138         OK
3    anita    92       95         187          A
4   bikash    74       80         154         OK
5    nisha    88       91         179          B
6   aayush    95       89         184          A
7     puja    81       85         166          B
8    rohan    69       74         143         OK
9    sneha    90       88         178          B
10   kiran    76       81         157         OK
11    amit    84       86         170          B
12  prabin    73       77         150         OK
13   suman    89       92         181          B
14    riya    91       94         185          A
15   nabin    65       70         135         OK
16  sarita    87       83         170          B
17  roshan    79       76         155         OK
18  manish    94       90         184          A
19    asha    82       87         169          B

In [13]:
df["BonusMath"]=df["Math"].map(lambda x:x+5)
df

      Name  Math  Science  TotalMarks Math_Grade  BonusMath
0      ram    78       82         160         OK         83
1     sita    85       79         164          B         90
2     hari    67       71         138         OK         72
3    anita    92       95         187          A         97
4   bikash    74       80         154         OK         79
5    nisha    88       91         179          B         93
6   aayush    95       89         184          A        100
7     puja    81       85         166          B         86
8    rohan    69       74         143         OK         74
9    sneha    90       88         178          B         95
10   kiran    76       81         157         OK         81
11    amit    84       86         170          B         89
12  prabin    73       77         150         OK         78
13   suman    89       92         181          B         94
14    riya    91       94         185          A         96
15   nabin    65       70         135         OK         70
16  sarita    87       83         170          B         92
17  roshan    79       76         155         OK         84
18  manish    94       90         184          A         99
19    asha    82       87         169          B         87